project_id = "zdaqwylzpkqojwvhlibd"

[functions.sync-playoff-teams]
verify_jwt = false

[functions.sync-playoff-players]
verify_jwt = false

[functions.test-playoff-team-players]
verify_jwt = false

[functions.sync-player-stats]
verify_jwt = false

[functions.sync-playoff-games]
verify_jwt = false

[functions.fetch-player-game-stats]
verify_jwt = false

[functions.upsert-player-week-stats]
verify_jwt = false

[functions.sync-player-stats-for-week]
verify_jwt = false

[functions.sync-season-players]
verify_jwt = false

[functions.send-auth-email]
verify_jwt = false
