project_id = "zdaqwylzpkqojwvhlibd"

[functions.sync-playoff-teams]
verify_jwt = false

[functions.sync-playoff-players]
verify_jwt = false

[functions.test-playoff-team-players]
verify_jwt = false

[functions.sync-player-stats]
verify_jwt = false
